import PDFDocument from 'pdfkit';
import { prisma } from '../config/database.js';

export interface ChallanPDFData {
  id: string;
  challanNumber: string;
  customerId: string;
  customer: {
    name: string;
    businessName?: string;
    email?: string;
    mobileNumber?: string;
    address?: string;
    gstNumber?: string;
  };
  status: string;
  totalQuantity: number;
  items: Array<{
    productNameSnapshot: string;
    skuSnapshot: string;
    unitPriceSnapshot: number;
    quantity: number;
    total: number;
  }>;
  creator: {
    fullName: string;
  };
  createdAt: Date;
  updatedAt: Date;
}

export class PDFService {
  static async generateChallanPDF(challanId: string): Promise<Buffer> {
    // Get challan data with all relationships
    const challan = await prisma.challan.findUnique({
      where: { id: challanId },
      include: {
        customer: true,
        items: true,
        creator: true,
      },
    });

    if (!challan) {
      throw new Error('Challan not found');
    }

    return new Promise((resolve, reject) => {
      try {
        const doc = new PDFDocument({ margin: 50 });
        const buffers: Buffer[] = [];

        doc.on('data', (chunk: Buffer) => buffers.push(chunk));
        doc.on('end', () => resolve(Buffer.concat(buffers)));
        doc.on('error', reject);

        // Generate PDF content
        this.generatePDFContent(doc, challan as ChallanPDFData);
        doc.end();
      } catch (error) {
        reject(error);
      }
    });
  }

  private static generatePDFContent(doc: PDFKit.PDFDocument, challan: ChallanPDFData) {
    const pageWidth = doc.page.width;
    const margin = 50;
    const contentWidth = pageWidth - 2 * margin;

    // Header
    doc.fontSize(24).font('Helvetica-Bold');
    doc.text('SALES CHALLAN', margin, margin, { align: 'center' });
    
    doc.fontSize(12).font('Helvetica');
    doc.text(`Challan No: ${challan.challanNumber}`, margin, margin + 40);
    doc.text(`Date: ${new Date(challan.createdAt).toLocaleDateString()}`, pageWidth - 200, margin + 40);
    doc.text(`Status: ${challan.status}`, pageWidth - 200, margin + 60);

    // Company Info (Left side)
    let yPos = margin + 100;
    doc.fontSize(14).font('Helvetica-Bold');
    doc.text('From:', margin, yPos);
    
    doc.fontSize(11).font('Helvetica');
    doc.text('Fundsroom Mini ERP', margin, yPos + 20);
    doc.text('Sales Department', margin, yPos + 35);
    doc.text('Generated by: ' + challan.creator.fullName, margin, yPos + 50);

    // Customer Info (Right side)
    doc.fontSize(14).font('Helvetica-Bold');
    doc.text('To:', margin + contentWidth/2, yPos);
    
    doc.fontSize(11).font('Helvetica');
    doc.text(challan.customer.name, margin + contentWidth/2, yPos + 20);
    if (challan.customer.businessName) {
      doc.text(challan.customer.businessName, margin + contentWidth/2, yPos + 35);
    }
    if (challan.customer.address) {
      doc.text(challan.customer.address, margin + contentWidth/2, yPos + 50, { width: contentWidth/2 - 50 });
    }
    if (challan.customer.mobileNumber) {
      doc.text('Phone: ' + challan.customer.mobileNumber, margin + contentWidth/2, yPos + 80);
    }
    if (challan.customer.email) {
      doc.text('Email: ' + challan.customer.email, margin + contentWidth/2, yPos + 95);
    }
    if (challan.customer.gstNumber) {
      doc.text('GST: ' + challan.customer.gstNumber, margin + contentWidth/2, yPos + 110);
    }

    // Items table
    yPos = yPos + 150;
    
    // Table header
    doc.fontSize(12).font('Helvetica-Bold');
    doc.rect(margin, yPos, contentWidth, 25).fillAndStroke('#f0f0f0', '#000');
    doc.fillColor('#000');
    
    const colWidths = {
      sno: 40,
      product: 180,
      sku: 80,
      qty: 60,
      price: 80,
      total: 80
    };
    
    let xPos = margin + 5;
    doc.text('S.No', xPos, yPos + 8);
    xPos += colWidths.sno;
    doc.text('Product Name', xPos, yPos + 8);
    xPos += colWidths.product;
    doc.text('SKU', xPos, yPos + 8);
    xPos += colWidths.sku;
    doc.text('Qty', xPos, yPos + 8);
    xPos += colWidths.qty;
    doc.text('Unit Price', xPos, yPos + 8);
    xPos += colWidths.price;
    doc.text('Total', xPos, yPos + 8);

    // Table rows
    yPos += 25;
    doc.fontSize(10).font('Helvetica');
    
    let grandTotal = 0;
    challan.items.forEach((item, index) => {
      if (yPos > doc.page.height - 150) {
        doc.addPage();
        yPos = margin;
      }

      // Alternate row coloring
      if (index % 2 === 1) {
        doc.rect(margin, yPos, contentWidth, 20).fillAndStroke('#f9f9f9', '#f9f9f9');
      }
      doc.fillColor('#000');

      xPos = margin + 5;
      doc.text((index + 1).toString(), xPos, yPos + 6);
      xPos += colWidths.sno;
      doc.text(item.productNameSnapshot, xPos, yPos + 6, { width: colWidths.product - 10 });
      xPos += colWidths.product;
      doc.text(item.skuSnapshot, xPos, yPos + 6);
      xPos += colWidths.sku;
      doc.text(item.quantity.toString(), xPos, yPos + 6);
      xPos += colWidths.qty;
      doc.text(`₹${item.unitPriceSnapshot.toFixed(2)}`, xPos, yPos + 6);
      xPos += colWidths.price;
      doc.text(`₹${item.total.toFixed(2)}`, xPos, yPos + 6);

      grandTotal += item.total;
      yPos += 20;
    });

    // Table border
    doc.rect(margin, yPos - (challan.items.length * 20), contentWidth, challan.items.length * 20).stroke('#000');

    // Totals
    yPos += 10;
    doc.fontSize(12).font('Helvetica-Bold');
    doc.text(`Total Quantity: ${challan.totalQuantity}`, margin, yPos);
    doc.text(`Grand Total: ₹${grandTotal.toFixed(2)}`, pageWidth - 150, yPos);

    // Footer
    yPos += 60;
    doc.fontSize(10).font('Helvetica');
    doc.text('Terms and Conditions:', margin, yPos);
    doc.text('1. Goods once sold will not be taken back.', margin, yPos + 15);
    doc.text('2. All disputes subject to local jurisdiction.', margin, yPos + 30);
    doc.text('3. Payment terms as per agreement.', margin, yPos + 45);

    // Signature
    yPos += 80;
    doc.text('Authorized Signatory', pageWidth - 150, yPos);
    doc.text('Fundsroom Mini ERP', pageWidth - 150, yPos + 20);

    // Generated info
    doc.fontSize(8);
    doc.text(`Generated on: ${new Date().toLocaleString()}`, margin, doc.page.height - 50);
    doc.text('This is a computer generated document.', margin, doc.page.height - 35);
  }
}